"""add reminder settings table

Revision ID: 33741bfabdf6
Revises: 0295fbe78644
Create Date: 2026-06-24 15:06:12.315595
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '33741bfabdf6'
down_revision: Union[str, None] = '0295fbe78644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('daily_checkin_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_checkin_time', sa.String(length=5), nullable=False),
    sa.Column('evening_shutdown_enabled', sa.Boolean(), nullable=False),
    sa.Column('evening_shutdown_time', sa.String(length=5), nullable=False),
    sa.Column('weekly_review_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_review_day', sa.String(length=10), nullable=False),
    sa.Column('weekly_review_time', sa.String(length=5), nullable=False),
    sa.Column('habit_nudge_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_settings')
    # ### end Alembic commands ###
