"""add habit library table

Revision ID: 88a8a7992050
Revises: 802de76b7158
Create Date: 2026-06-24 14:28:07.501427
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '88a8a7992050'
down_revision: Union[str, None] = '802de76b7158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_library',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('benefit', sa.Text(), nullable=False),
    sa.Column('how_to_start', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_library')
    # ### end Alembic commands ###
