from sqlalchemy.orm import Session

from app.models.habit_library import HabitLibraryItem

LIBRARY_ITEMS = [
    {
        "name": "Sin telefono la primera hora",
        "category": "bienestar",
        "description": "Evitar el celular durante los primeros 60 minutos despues de despertar. Permite que tu mente arranque sin estimulos externos.",
        "benefit": "Menor ansiedad matutina, mejor enfoque inicial, reduces el impulso de scroll.",
        "how_to_start": "Deja el celular en otra habitacion o en modo avion. Usa un despertador fisico si lo necesitas.",
        "difficulty": "medium",
        "daily_minutes": 60,
        "evidence_type": "personal",
        "source": "Recomendacion comun en productividad personal. Consistente con investigacion sobre atencion y dopamina.",
    },
    {
        "name": "Sin redes antes de dormir",
        "category": "sueno",
        "description": "Dejar redes sociales y pantallas estimulantes al menos 1 hora antes de acostarte.",
        "benefit": "Mejor calidad de sueno, menos tiempo para conciliar el sueno, mente mas tranquila.",
        "how_to_start": "Pon un recordatorio 1 hora antes de tu hora de dormir. Sustituye con lectura o journaling.",
        "difficulty": "medium",
        "daily_minutes": 60,
        "evidence_type": "science",
        "source": "Estudios sobre luz azul y melatonina. La exposicion a pantallas antes de dormir se asocia con peor calidad de sueno (revisiones en Sleep Medicine Reviews).",
    },
    {
        "name": "Caminar 10 min despues de comer",
        "category": "salud",
        "description": "Una caminata corta de 10 minutos despues del almuerzo o la cena.",
        "benefit": "Mejora digestion, regula glucosa en sangre, reduce somnolencia post-comida.",
        "how_to_start": "Despues de tu comida principal, sal a caminar. No tiene que ser rapido. 10 minutos bastan.",
        "difficulty": "low",
        "daily_minutes": 10,
        "evidence_type": "science",
        "source": "Estudios en Diabetes Care y Sports Medicine muestran que caminar post-comida mejora control glucemico.",
    },
    {
        "name": "Meditacion de respiracion 5 min",
        "category": "bienestar",
        "description": "Sentarte en silencio y observar tu respiracion durante 5 minutos. Cuando la mente se va, vuelves.",
        "benefit": "Reduce estres, mejora atencion, ayuda a regular emociones.",
        "how_to_start": "Sientate comodo, cierra los ojos, respira normal. Solo observa. Empieza con 3 min si 5 es mucho.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "science",
        "source": "Meta-analisis en JAMA Internal Medicine confirman beneficios de mindfulness en ansiedad, depresion y dolor.",
    },
    {
        "name": "Lectura nocturna 10 min",
        "category": "desarrollo",
        "description": "Leer un libro fisico o e-reader sin luz azul durante 10-15 minutos antes de dormir.",
        "benefit": "Habito de lectura sostenible, mejor transicion al sueno, aprendizaje acumulado.",
        "how_to_start": "Ten un libro en tu mesa de noche. Lee al menos 1 pagina. El habito importa mas que la cantidad.",
        "difficulty": "low",
        "daily_minutes": 10,
        "evidence_type": "personal",
        "source": "Practica comun recomendada por educadores. Los beneficios de lectura regular tienen respaldo general.",
    },
    {
        "name": "Repaso espaciado",
        "category": "estudio",
        "description": "Revisar material en intervalos crecientes (1 dia, 3 dias, 7 dias) en lugar de todo junto antes del examen.",
        "benefit": "Retencion significativamente mayor. Una de las tecnicas de aprendizaje mejor respaldadas.",
        "how_to_start": "Despues de estudiar un tema, revisalo al dia siguiente, a los 3 dias, luego a la semana. Usa flashcards.",
        "difficulty": "medium",
        "daily_minutes": 15,
        "evidence_type": "science",
        "source": "Respaldo solido en psicologia cognitiva. Ebbinghaus (curva del olvido), estudios de Cepeda et al. en Psychological Bulletin.",
    },
    {
        "name": "Tecnica Pomodoro",
        "category": "estudio",
        "description": "Trabajar en bloques de 25 minutos de enfoque total, seguidos de 5 minutos de descanso.",
        "benefit": "Reduce procrastinacion, mantiene enfoque, hace tareas largas manejables.",
        "how_to_start": "Elige una tarea, pon timer de 25 min, trabaja sin interrupciones. Descansa 5 min. Repite.",
        "difficulty": "low",
        "daily_minutes": 30,
        "evidence_type": "personal",
        "source": "Creada por Francesco Cirillo. No tiene estudios controlados propios, pero coincide con investigacion sobre atencion sostenida.",
    },
    {
        "name": "Journaling de 3 lineas",
        "category": "salud_mental",
        "description": "Cada noche, escribe 3 lineas: que paso, como te sentiste, que podrias mejorar.",
        "benefit": "Claridad mental, procesamiento emocional, autoconocimiento gradual.",
        "how_to_start": "Ten un cuaderno junto a tu cama. Antes de dormir, 3 lineas. No necesita ser profundo.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "science",
        "source": "La escritura expresiva tiene respaldo en psicologia (estudios de Pennebaker). Se usa en terapia cognitivo-conductual.",
    },
    {
        "name": "Meal prep dominical",
        "category": "alimentacion",
        "description": "Dedicar 1-2 horas el domingo a cocinar base de la semana: arroz, frijol, pollo, huevos duros.",
        "benefit": "Ahorro de dinero, comes mas saludable, menos decisiones diarias sobre comida.",
        "how_to_start": "El domingo despues de comprar, cocina arroz, frijol y una proteina. Guarda en recipientes.",
        "difficulty": "medium",
        "daily_minutes": 15,
        "evidence_type": "personal",
        "source": "Practica comun en nutricion practica. La planificacion alimentaria se asocia con mejor dieta.",
    },
    {
        "name": "Beber agua al despertar",
        "category": "salud",
        "description": "Tomar un vaso de agua (250-500 ml) inmediatamente despues de despertar.",
        "benefit": "Rehidratacion despues de horas sin agua, activa metabolismo, mejora alerta.",
        "how_to_start": "Deja un vaso o botella de agua junto a tu cama. Al despertar, tomalo primero.",
        "difficulty": "low",
        "daily_minutes": 1,
        "evidence_type": "personal",
        "source": "Recomendacion comun en salud general. La deshidratacion leve afecta cognicion (Journal of Nutrition).",
    },
    {
        "name": "Kaizen: mejora del 1% diario",
        "category": "filosofia",
        "description": "Filosofia japonesa de mejora continua. Haz una mejora pequena cada dia en cualquier area.",
        "benefit": "Progreso sostenible sin agotamiento. Las mejoras pequenas se acumulan.",
        "how_to_start": "Preguntate: que puedo hacer 1% mejor hoy? Puede ser ordenar un cajon o estudiar 5 min mas.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "tradition",
        "source": "Filosofia de gestion japonesa (Toyota). El principio de mejora incremental tiene paralelos en psicologia del comportamiento.",
    },
    {
        "name": "Revision estoica diaria",
        "category": "filosofia",
        "description": "Al final del dia: que estuvo en mi control? Que no? Que hice bien? Que puedo mejorar?",
        "benefit": "Reduce ansiedad por cosas fuera de tu control, fomenta responsabilidad personal.",
        "how_to_start": "Antes de dormir, hazte las 3 preguntas. Puedes escribirlas o pensarlas. No mas de 5 min.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "tradition",
        "source": "Practica de Epicteto y Marco Aurelio. La reinterpretacion de pensamientos tiene eco en terapia cognitivo-conductual.",
    },
    {
        "name": "Hara hachi bu: comer al 80%",
        "category": "alimentacion",
        "description": "Principio de Okinawa: dejar de comer cuando sientes 80% de saciedad.",
        "benefit": "Menor ingesta calorica sin contar calorias, mejor digestion, control de peso.",
        "how_to_start": "Come mas despacio. A mitad de comida, pausa y preguntate si aun tienes hambre real.",
        "difficulty": "medium",
        "daily_minutes": 0,
        "evidence_type": "tradition",
        "source": "Tradicion de Okinawa, zona azul de longevidad. La restriccion calorica moderada tiene respaldo, pero el principio especifico es cultural.",
        "warning": "No es una dieta restrictiva. Si tienes historial de trastornos alimentarios, consulta a un profesional.",
    },
    {
        "name": "Escritorio limpio antes de estudiar",
        "category": "orden",
        "description": "Antes de estudiar o trabajar, dedica 2-3 minutos a despejar tu escritorio.",
        "benefit": "Menor distraccion visual, transicion mental hacia el enfoque.",
        "how_to_start": "Antes de abrir libros o laptop, retira todo lo que no necesitas. Tarda 2 minutos.",
        "difficulty": "low",
        "daily_minutes": 3,
        "evidence_type": "personal",
        "source": "Recomendacion comun en productividad. Investigacion limitada sugiere que el desorden visual compite por atencion.",
    },
    {
        "name": "Registrar gastos diarios",
        "category": "finanzas",
        "description": "Anotar cada gasto del dia: que compraste y cuanto. Una linea por gasto.",
        "benefit": "Conciencia de a donde va tu dinero, identificas gastos innecesarios.",
        "how_to_start": "Lleva una nota en el celular. Cada gasto: Almuerzo Q25, Pasaje Q5. Revisa el total cada noche.",
        "difficulty": "low",
        "daily_minutes": 3,
        "evidence_type": "personal",
        "source": "Practica basica de finanzas personales recomendada por educadores financieros.",
    },
    {
        "name": "Ingles diario 15 min",
        "category": "aprendizaje",
        "description": "15 minutos diarios mezclando input (escuchar/leer) y output (hablar/escribir).",
        "benefit": "Progreso constante. 15 min diarios supera a 2 horas el fin de semana.",
        "how_to_start": "Elige un podcast corto en ingles, escucha 10 min, escribe 3 oraciones sobre lo que entendiste.",
        "difficulty": "low",
        "daily_minutes": 15,
        "evidence_type": "science",
        "source": "La practica distribuida es superior para idiomas (investigacion en Applied Linguistics).",
    },
    {
        "name": "Sueno a hora fija",
        "category": "sueno",
        "description": "Acostarte y levantarte a la misma hora todos los dias, incluso fines de semana.",
        "benefit": "Mejor calidad de sueno, mas energia, regula ritmo circadiano.",
        "how_to_start": "Elige hora de dormir y despertar. Pon alarma para ambas. Fines de semana, max 1 hora de desvio.",
        "difficulty": "medium",
        "daily_minutes": 0,
        "evidence_type": "science",
        "source": "Respaldo solido en medicina del sueno (American Academy of Sleep Medicine, Sleep journal).",
        "warning": "Si tienes insomnio persistente o somnolencia excesiva, consulta a un medico.",
    },
]


def seed_library(db: Session):
    existing = db.query(HabitLibraryItem).count()
    if existing > 0:
        return
    for item in LIBRARY_ITEMS:
        db.add(HabitLibraryItem(**item))
    db.commit()
