from sqlalchemy.orm import Session

from app.models.habit_library import HabitLibraryItem

LIBRARY_ITEMS = [
    {
        "name": "Sin telefono la primera hora",
        "category": "bienestar",
        "description": "Evitar el celular durante los primeros 60 minutos despues de despertar. Puede ayudar a que tu mente arranque sin estimulos externos.",
        "benefit": "Suele reducir ansiedad matutina, puede mejorar enfoque inicial y reducir el impulso de scroll.",
        "how_to_start": "Deja el celular en otra habitacion o en modo avion. Usa un despertador fisico si lo necesitas.",
        "difficulty": "medium",
        "daily_minutes": 60,
        "evidence_type": "personal",
        "source": "Recomendacion comun en productividad personal. Consistente con investigacion sobre atencion y dopamina, pero sin estudios controlados especificos.",
    },
    {
        "name": "Sin redes antes de dormir",
        "category": "sueno",
        "description": "Dejar redes sociales y pantallas estimulantes al menos 1 hora antes de acostarte.",
        "benefit": "Puede mejorar calidad de sueno, reducir tiempo para conciliar el sueno y calmar la mente.",
        "how_to_start": "Pon un recordatorio 1 hora antes de tu hora de dormir. Sustituye con lectura o journaling.",
        "difficulty": "medium",
        "daily_minutes": 60,
        "evidence_type": "science",
        "source": "La exposicion a pantallas antes de dormir se asocia con peor calidad de sueno en revisiones publicadas en Sleep Medicine Reviews.",
    },
    {
        "name": "Caminar 10 min despues de comer",
        "category": "salud",
        "description": "Una caminata corta de 10 minutos despues del almuerzo o la cena.",
        "benefit": "Puede mejorar digestion, ayuda a regular glucosa en sangre y suele reducir somnolencia post-comida.",
        "how_to_start": "Despues de tu comida principal, sal a caminar. No tiene que ser rapido. 10 minutos bastan.",
        "difficulty": "low",
        "daily_minutes": 10,
        "evidence_type": "science",
        "source": "Estudios publicados en Diabetes Care y Sports Medicine sugieren que caminar post-comida puede mejorar control glucemico.",
    },
    {
        "name": "Meditacion de respiracion 5 min",
        "category": "bienestar",
        "description": "Sentarte en silencio y observar tu respiracion durante 5 minutos. Cuando la mente se va, vuelves.",
        "benefit": "Puede ayudar a reducir estres, suele mejorar la atencion y apoyar la regulacion emocional.",
        "how_to_start": "Sientate comodo, cierra los ojos, respira normal. Solo observa. Empieza con 3 min si 5 es mucho.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "science",
        "source": "Meta-analisis publicados en JAMA Internal Medicine muestran beneficios de mindfulness en ansiedad, depresion y manejo del dolor.",
    },
    {
        "name": "Lectura nocturna 10 min",
        "category": "desarrollo",
        "description": "Leer un libro fisico o e-reader sin luz azul durante 10-15 minutos antes de dormir.",
        "benefit": "Es una practica comun para construir habito de lectura, puede facilitar la transicion al sueno.",
        "how_to_start": "Ten un libro en tu mesa de noche. Lee al menos 1 pagina. El habito importa mas que la cantidad.",
        "difficulty": "low",
        "daily_minutes": 10,
        "evidence_type": "personal",
        "source": "Practica comun recomendada por educadores y autores de habitos. Los beneficios de lectura regular tienen respaldo general pero no hay estudios sobre el horario especifico.",
    },
    {
        "name": "Repaso espaciado",
        "category": "estudio",
        "description": "Revisar material en intervalos crecientes (1 dia, 3 dias, 7 dias) en lugar de todo junto antes del examen.",
        "benefit": "Tiene respaldo solido para mejorar retencion a largo plazo. Es una de las tecnicas de aprendizaje mejor estudiadas.",
        "how_to_start": "Despues de estudiar un tema, revisalo al dia siguiente, a los 3 dias, luego a la semana. Usa flashcards.",
        "difficulty": "medium",
        "daily_minutes": 15,
        "evidence_type": "science",
        "source": "Respaldo solido en psicologia cognitiva: curva del olvido de Ebbinghaus, estudios de Cepeda et al. publicados en Psychological Bulletin.",
    },
    {
        "name": "Tecnica Pomodoro",
        "category": "estudio",
        "description": "Trabajar en bloques de 25 minutos de enfoque total, seguidos de 5 minutos de descanso.",
        "benefit": "Muchos usuarios reportan que reduce procrastinacion y hace las tareas largas mas manejables.",
        "how_to_start": "Elige una tarea, pon timer de 25 min, trabaja sin interrupciones. Descansa 5 min. Repite.",
        "difficulty": "low",
        "daily_minutes": 30,
        "evidence_type": "personal",
        "source": "Creada por Francesco Cirillo. No tiene estudios controlados propios, pero coincide con investigacion general sobre atencion sostenida y descansos.",
    },
    {
        "name": "Journaling de 3 lineas",
        "category": "salud_mental",
        "description": "Cada noche, escribe 3 lineas: que paso, como te sentiste, que podrias mejorar.",
        "benefit": "Puede aportar claridad mental, apoyar procesamiento emocional y fomentar autoconocimiento.",
        "how_to_start": "Ten un cuaderno junto a tu cama. Antes de dormir, 3 lineas. No necesita ser profundo.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "science",
        "source": "La escritura expresiva tiene respaldo en psicologia (estudios de Pennebaker). El journaling estructurado se usa como herramienta en terapia cognitivo-conductual.",
    },
    {
        "name": "Meal prep dominical",
        "category": "alimentacion",
        "description": "Dedicar 1-2 horas el domingo a cocinar base de la semana: arroz, frijol, pollo, huevos duros.",
        "benefit": "Suele ayudar a ahorrar dinero, comer mas saludable y reducir decisiones diarias sobre comida.",
        "how_to_start": "El domingo despues de comprar, cocina arroz, frijol y una proteina. Guarda en recipientes.",
        "difficulty": "medium",
        "daily_minutes": 15,
        "evidence_type": "personal",
        "source": "Practica comun en nutricion practica y economia domestica. La planificacion alimentaria se asocia con mejor dieta en estudios observacionales.",
    },
    {
        "name": "Beber agua al despertar",
        "category": "salud",
        "description": "Tomar un vaso de agua (250-500 ml) inmediatamente despues de despertar.",
        "benefit": "Puede ayudar a rehidratarse despues de horas sin agua. La hidratacion adecuada apoya la funcion cognitiva.",
        "how_to_start": "Deja un vaso o botella de agua junto a tu cama. Al despertar, tomalo primero.",
        "difficulty": "low",
        "daily_minutes": 1,
        "evidence_type": "personal",
        "source": "Recomendacion comun en salud general. La deshidratacion leve puede afectar cognicion (estudios en Journal of Nutrition), pero el timing al despertar no tiene estudios controlados.",
    },
    {
        "name": "Kaizen: mejora del 1% diario",
        "category": "filosofia",
        "description": "Filosofia japonesa de mejora continua. En vez de cambios grandes, busca una mejora pequena cada dia.",
        "benefit": "Puede facilitar progreso sostenible sin agotamiento. Las mejoras pequenas tienden a acumularse con el tiempo.",
        "how_to_start": "Preguntate: que puedo hacer un poco mejor hoy? Puede ser ordenar un cajon o estudiar 5 min mas.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "tradition",
        "source": "Filosofia de gestion japonesa adoptada en manufactura (Toyota) y desarrollo personal. Es una tradicion, no un metodo validado cientificamente.",
    },
    {
        "name": "Revision estoica diaria",
        "category": "filosofia",
        "description": "Al final del dia: que estuvo en mi control? Que no? Que hice bien? Que puedo mejorar?",
        "benefit": "Puede ayudar a reducir ansiedad por cosas fuera de tu control y fomentar responsabilidad personal.",
        "how_to_start": "Antes de dormir, hazte las 3 preguntas. Puedes escribirlas o pensarlas. No mas de 5 min.",
        "difficulty": "low",
        "daily_minutes": 5,
        "evidence_type": "tradition",
        "source": "Practica de Epicteto y Marco Aurelio. Es tradicion filosofica, no ciencia. La parte de reinterpretar pensamientos tiene paralelos con terapia cognitivo-conductual, que si tiene evidencia.",
    },
    {
        "name": "Hara hachi bu: comer al 80%",
        "category": "alimentacion",
        "description": "Principio de Okinawa: dejar de comer cuando sientes 80% de saciedad.",
        "benefit": "Puede contribuir a menor ingesta calorica, mejor digestion y control de peso a largo plazo.",
        "how_to_start": "Come mas despacio. A mitad de comida, pausa y preguntate si aun tienes hambre real.",
        "difficulty": "medium",
        "daily_minutes": 0,
        "evidence_type": "tradition",
        "source": "Tradicion de Okinawa, zona azul de longevidad. El principio especifico es cultural. La restriccion calorica moderada tiene respaldo razonable en investigacion, pero no este metodo en particular.",
        "warning": "No es una dieta restrictiva. Si tienes historial de trastornos alimentarios, consulta a un profesional antes de cambiar habitos alimentarios.",
    },
    {
        "name": "Escritorio limpio antes de estudiar",
        "category": "orden",
        "description": "Antes de estudiar o trabajar, dedica 2-3 minutos a despejar tu escritorio.",
        "benefit": "Suele reducir distraccion visual y facilitar la transicion mental hacia el enfoque.",
        "how_to_start": "Antes de abrir libros o laptop, retira todo lo que no necesitas. Tarda 2 minutos.",
        "difficulty": "low",
        "daily_minutes": 3,
        "evidence_type": "personal",
        "source": "Recomendacion comun en productividad. Hay investigacion limitada que sugiere que el desorden visual puede competir por atencion, pero la practica especifica es experiencial.",
    },
    {
        "name": "Registrar gastos diarios",
        "category": "finanzas",
        "description": "Anotar cada gasto del dia: que compraste y cuanto. Una linea por gasto.",
        "benefit": "Suele aumentar conciencia de a donde va tu dinero y ayuda a identificar gastos innecesarios.",
        "how_to_start": "Lleva una nota en el celular. Cada gasto: Almuerzo Q25, Pasaje Q5. Revisa el total cada noche.",
        "difficulty": "low",
        "daily_minutes": 3,
        "evidence_type": "personal",
        "source": "Practica basica de finanzas personales recomendada por educadores financieros. No hay estudios controlados sobre el metodo especifico.",
    },
    {
        "name": "Ingles diario 15 min",
        "category": "aprendizaje",
        "description": "15 minutos diarios mezclando input (escuchar/leer) y output (hablar/escribir).",
        "benefit": "La practica distribuida suele ser mas efectiva que sesiones largas esporadicas para adquirir un idioma.",
        "how_to_start": "Elige un podcast corto en ingles, escucha 10 min, escribe 3 oraciones sobre lo que entendiste.",
        "difficulty": "low",
        "daily_minutes": 15,
        "evidence_type": "science",
        "source": "La practica distribuida tiene respaldo razonable para adquisicion de idiomas (investigacion en Applied Linguistics y Second Language Research).",
    },
    {
        "name": "Sueno a hora fija",
        "category": "sueno",
        "description": "Acostarte y levantarte a la misma hora todos los dias, incluso fines de semana.",
        "benefit": "Puede mejorar calidad de sueno, aumentar energia al despertar y regular el ritmo circadiano.",
        "how_to_start": "Elige hora de dormir y despertar. Pon alarma para ambas. Fines de semana, max 1 hora de desvio.",
        "difficulty": "medium",
        "daily_minutes": 0,
        "evidence_type": "science",
        "source": "Tiene respaldo solido en medicina del sueno. La regularidad del sueno es un factor clave segun la American Academy of Sleep Medicine.",
        "warning": "Si tienes insomnio persistente o somnolencia excesiva, consulta a un medico. La higiene del sueno no sustituye evaluacion profesional.",
    },
]


def seed_library(db: Session):
    existing = db.query(HabitLibraryItem).count()
    if existing > 0:
        return
    for item in LIBRARY_ITEMS:
        db.add(HabitLibraryItem(**item))
    db.commit()
